spring:
  data:
    jpa.repositories.enabled: true
  datasource:
    initialization-mode: always
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-157-15-228.compute-1.amazonaws.com:5432/dd0jjo5eilekaa?sslmode=require
    username: ykooqrxfyakszz
    password: 24d99463a84c3b7df1db569ef11dd1dd45ae1df8a5221c1b1833f5b5c11c0347
    continueOnError: true