spring:
  data:
    jpa.repositories.enabled: true
  datasource:
    initialization-mode: always
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ec2-3-221-109-227.compute-1.amazonaws.com:5432/d31mmdqh0krbg?sslmode=require
    username: kihmohdqwadvcz
    password: f3036633fb10e04de4b8a2c3dd0e755968813083f4c7e6e0ee1d0b7c2cea0207
    continueOnError: true