spring:
  data:
    jpa.repositories.enabled: true
  datasource:
    initialization-mode: always
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ec2-3-225-79-57.compute-1.amazonaws.com:5432/dtpgtfvk5f9vn?sslmode=require
    username: nguhsuvfcatblh
    password: 73703e517d13a5916b7363b0813ec7968cbc8318efb2fd22508a6f69d44a2cf0
    continueOnError: true