spring:
  data:
    jpa.repositories.enabled: true
  datasource:
    initialization-mode: always
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-235-98-1.compute-1.amazonaws.com:5432/d5s5je782nnij4?sslmode=require
    username: lerysusrygmyzv
    password: 7200e3f5e9c99c346e466fba9db20ff2d3235ae345683606cd4057f918bd51d7
    continueOnError: true